name: Deployment
on:
  push:
    branches:
      - main
      - dev
env:
  MONGODB_DB_NAME: db-demo
jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.cns99pv.mongodb.net
      MONGODB_USERNAME: yasserfathi888
      MONGODB_PASSWORD: vxJfkpCeohsp2cvF
      PORT: 8080 
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: echo "MONGODB_USERNAME:${{ env.MONGODB_USERNAME }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output informationfdfdf
        run: |        
          echo "..."
